// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH2W55aZt1S8v2juTukL-EZgu0bX9WEMI',
    appId: '1:907556109889:web:0d5fa18f905046483750c0',
    messagingSenderId: '907556109889',
    projectId: 'sport-lottery-9d11f',
    authDomain: 'sport-lottery-9d11f.firebaseapp.com',
    storageBucket: 'sport-lottery-9d11f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0_y7N3RtVCc8aVvzWDwDCIPrUrtQUvkk',
    appId: '1:907556109889:android:140a80976b7409193750c0',
    messagingSenderId: '907556109889',
    projectId: 'sport-lottery-9d11f',
    storageBucket: 'sport-lottery-9d11f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv5N8cXRFwy7_ffXRGcA_mV4KL9Rx2EjM',
    appId: '1:907556109889:ios:40768deadca8fba73750c0',
    messagingSenderId: '907556109889',
    projectId: 'sport-lottery-9d11f',
    storageBucket: 'sport-lottery-9d11f.appspot.com',
    androidClientId: '907556109889-2f39dsftdih1v2vpc8phpm2rrmqks1d4.apps.googleusercontent.com',
    iosClientId: '907556109889-6avu9ltbk93n4p172j3u0687f9hvvdmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sportLottery',
  );
}
